server:
  port: 8081
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        type: trace
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:user
    username: root
    password: 542865
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp    username: ZW1haWxzZW5kZXIyNThAZ21haWwuY29t
    password: UGtwMjVqNjcqTG1uaw==
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          connection-timeout: 1000
          ssl:
            trust: smtp.gmail.com
  
messages:
  genericError: Error
  genericInfo: Info
  errorToGeneratePasswordEncrypted: There was a error while trying to encrypt password
  userAlreadyRegistered: User already registered!
  wrongPasswordOrEmail: The given password or email does not match. 
  emailNotValid: The given email is not valid.
  emailDoesNotMatch: The emails are not the same.
  userNotFound: User not found.
  oldPasswordDoesNotMatch: The given old password does not match.
  passwordChangedSucess: Password was changed!
  emailSendSucess: The reminder of password was send to email %s
  emailSendError: There was a error while trying to send a email with cause %s
  emailReminderPasswordMessage: Here are your reminder password %s
  resetPasswordEmailSubject: Reminder Password