spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        type: trace
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:user
    username: root
    password: 542865
  
messages:
  genericError: Error
  genericInfo: Info
  errorToGeneratePasswordEncrypted: There was a error while trying to encrypt password
  userAlreadyRegistered: User already registered!
  wrongPasswordOrEmail: The given password or email does not match. 
  emailNotValid: The given email is not valid.
  emailDoesNotMatch: The emails are not the same.
  userNotFound: User not found.
  oldPasswordDoesNotMatch: The given old password does not match.
  passwordChangedSucess: Password was changed!
  emailSendSucess: The reminder of password was send to email %s
  emailSendError: There was a error while trying to send a email with cause %s
  emailReminderPasswordMessage: Here are your reminder password %s
  resetPasswordEmailSubject: Reminder Password